Repository nadiasGame/power.dolphins, pull requests merged in 2022-04, with the labels that each got.

#34 Created template add and remove books Redux store
  src/actions/bookActions.js
  src/index.js
  src/reducers/booksReducer.js
  src/reducers/cartReducer.js
Labels: enhancement

#37 comment out localStorage for now
  src/index.js
Labels: wontfix

#48 #33 added login with a check
  src/components/book.js
  src/views/Admin.js
  src/views/Login.js
Labels: enhancement

#58 #56 you can now logout
  src/App.js
  src/components/Header.css
  src/components/Header.js
Labels: enhancement

#62 #60 happy?
  src/views/Login.js
Labels: epic
